name: Latest book list from a goodreads
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  update-readme-with-goodreads-books:
    name: Update this repo's README with what you're currently reading
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: zwacky/goodreads-profile-workflow@main
        with:
          goodreads_user_id: "139684603"
          shelf: "currently-reading"
          comment_tag_name: "GOODREADS-READING-LIST"
      - uses: zwacky/goodreads-profile-workflow@main
        with:
          goodreads_user_id: "139684603"
          shelf: "read"
          max_books_count: 3
          sort_by_fields: ">user_read_at"
          comment_tag_name: "GOODREADS-READ-LIST"
      - uses: zwacky/goodreads-profile-workflow@main
        with:
          goodreads_user_id: "139684603"
          shelf: "backlog"
          comment_tag_name: "GOODREADS-SHELF-LIST"
          sort_by_fields: ">average_rating"
